name: main branch auto ci process script
on:
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/Server-V2
            git pull origin main
            pm2 kill
            npm i --force
            npm run build
            pm2 start dist/main.js
      - name: set up environment variables
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} >> $GITHUB_ENV
          echo ${{ secrets.AWS_BUCKET_NAME }} >> $GITHUB_ENV
          echo ${{ secrets.AWS_BUCKET_REGION }} >> $GITHUB_ENV
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> $GITHUB_ENV
          echo ${{ secrets.CALLBACK_URL }} >> $GITHUB_ENV
          echo ${{ secrets.DATABASE_HOST }} >> $GITHUB_ENV
          echo ${{ secrets.DATABASE_NAME }} >> $GITHUB_ENV
          echo ${{ secrets.DATABASE_PASSWORD }} >> $GITHUB_ENV
          echo ${{ secrets.DATABASE_PORT }} >> $GITHUB_ENV
          echo ${{ secrets.DATABASE_USERNAME }} >> $GITHUB_ENV
          echo ${{ secrets.JAVASCRIPT_KEY }} >> $GITHUB_ENV
          echo ${{ secrets.PASSWORD }} >> $GITHUB_ENV
          echo ${{ secrets.PORT }} >> $GITHUB_ENV
          echo ${{ secrets.REDIS_HOST }} >> $GITHUB_ENV
          echo ${{ secrets.REDIS_PASSWORD }} >> $GITHUB_ENV
          echo ${{ secrets.REDIS_PORT }} >> $GITHUB_ENV
          echo ${{ secrets.REDIS_USERNAME }} >> $GITHUB_ENV
          echo ${{ secrets.RESTAPI_KEY }} >> $GITHUB_ENV
          echo ${{ secrets.S3_ACCESSKEY }} >> $GITHUB_ENV
          echo ${{ secrets.S3_SECRETKEY }} >> $GITHUB_ENV
          echo ${{ secrets.USEREMAIL }} >> $GITHUB_ENV
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      JAVASCRIPT_KEY: ${{ secrets.JAVASCRIPT_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT: ${{ secrets.PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
      RESTAPI_KEY: ${{ secrets.RESTAPI_KEY }}
      S3_ACCESSKEY: ${{ secrets.S3_ACCESSKEY }}
      S3_SECRETKEY: ${{ secrets.S3_SECRETKEY }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
